from django.conf import settings
from django.db import models


class QuestionnaireSession(models.Model):
    STATUS_CHOICES = [
        ("in_progress", "In Progress"),
        ("completed", "Completed"),
        ("abandoned", "Abandoned"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="questionnaire_sessions",
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="in_progress")
    current_question_order = models.IntegerField(default=0)
    started_at = models.DateTimeField(auto_now_add=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f"Session {self.id} - {self.user.username} ({self.status})"


class AIQuestion(models.Model):
    """A question dynamically generated by Gemini for a specific session."""

    TYPE_CHOICES = [
        ("free_text", "Free Text"),
        ("single_choice", "Single Choice"),
        ("multi_choice", "Multiple Choice"),
    ]

    session = models.ForeignKey(
        QuestionnaireSession,
        on_delete=models.CASCADE,
        related_name="ai_questions",
    )
    order = models.IntegerField()
    text = models.TextField()
    question_type = models.CharField(max_length=20, choices=TYPE_CHOICES, default="free_text")
    options = models.JSONField(default=list, blank=True)
    topic = models.CharField(max_length=100, blank=True)
    source = models.CharField(max_length=20, default="gemini")
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["order"]
        unique_together = ["session", "order"]

    def __str__(self):
        return f"AIQ#{self.order} [{self.session_id}]: {self.text[:60]}"


class AIAnswer(models.Model):
    """User's answer to an AI-generated question."""

    session = models.ForeignKey(
        QuestionnaireSession,
        on_delete=models.CASCADE,
        related_name="ai_answers",
    )
    question = models.ForeignKey(
        AIQuestion,
        on_delete=models.CASCADE,
        related_name="answers",
    )
    text_response = models.TextField(blank=True)
    selected_options = models.JSONField(default=list, blank=True)
    answered_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["session", "question"]

    def __str__(self):
        return f"AIAnswer to Q#{self.question.order} in session {self.session_id}"

    def get_answer_text(self) -> str:
        parts = []
        if self.text_response:
            parts.append(self.text_response)
        if self.selected_options:
            parts.extend(self.selected_options)
        return " ".join(parts)
