# Generated by Django 5.2.15 on 2026-06-16 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ATSResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('trending', 'Trending Job'), ('vacancy', 'Live Vacancy')], default='trending', max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('job_description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('content', models.TextField()),
                ('keywords_included', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trending_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ats_resumes', to='jobs.trendingjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ats_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
