# Generated by Django 5.2.14 on 2026-06-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_drop_embedding'),
        ('recommendations', '0002_ai_generated'),
        ('skills', '0002_drop_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='gap_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='careers.skillgapreport'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='target_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_recommendations', to='skills.skill'),
        ),
    ]
