# Generated by Django 5.2.14 on 2026-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_recommendation_target_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_primary_for_gap',
            field=models.BooleanField(default=False),
        ),
    ]
