# Generated by Django 5.2.14 on 2026-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_drop_embedding'),
        ('recommendations', '0004_recommendation_is_primary_for_gap'),
        ('skills', '0002_drop_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='provider',
            field=models.CharField(blank=True, choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('edx', 'edX'), ('mit_ocw', 'MIT OpenCourseWare'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('aws', 'AWS'), ('university', 'University'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='source',
            field=models.CharField(blank=True, choices=[('curated', 'Curated'), ('web_search', 'Web Search'), ('ai', 'AI Generated')], default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['provider', 'level'], name='recommendat_provide_40ddbb_idx'),
        ),
        migrations.AddIndex(
            model_name='learningresource',
            index=models.Index(fields=['source', 'level'], name='recommendat_source_c2dd37_idx'),
        ),
    ]
