# Generated by Django 5.2.14 on 2026-05-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('tool', 'Tool'), ('domain', 'Domain Knowledge')], default='technical', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_detected', models.JSONField(default=list)),
                ('experience_years', models.FloatField(default=0.0)),
                ('education', models.JSONField(default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('employability_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='users.resumeupload')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.IntegerField(default=1)),
                ('source', models.CharField(choices=[('resume', 'Resume'), ('questionnaire', 'Questionnaire'), ('manual', 'Manual'), ('ai', 'AI Detection')], default='manual', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
