# Generated by Django 5.2.14 on 2026-05-19 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('free_text', 'Free Text'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice')], default='free_text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='fallback', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_questions', to='questionnaire.questionnairesession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
        migrations.CreateModel(
            name='AIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_response', models.TextField(blank=True)),
                ('selected_options', models.JSONField(blank=True, default=list)),
                ('nlp_entities', models.JSONField(blank=True, default=dict)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_answers', to='questionnaire.questionnairesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.aiquestion')),
            ],
            options={
                'unique_together': {('session', 'question')},
            },
        ),
    ]
