# Generated by Django 5.2.14 on 2026-05-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('required_traits', models.JSONField(blank=True, default=dict)),
                ('domain_embedding', models.JSONField(blank=True, default=list)),
                ('is_technical', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employability_score', models.FloatField(default=0.0)),
                ('missing_skills', models.JSONField(default=list)),
                ('prioritized_skills', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_pct', models.FloatField()),
                ('rank', models.IntegerField()),
                ('explanation_text', models.TextField(blank=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerdomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField(default=3)),
                ('min_proficiency', models.IntegerField(default=2)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='careers.careerdomain')),
            ],
        ),
    ]
