# Generated by Django 5.2.14 on 2026-05-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerskillrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerdomain'),
        ),
        migrations.AddField(
            model_name='skillgapreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='careerskillrequirement',
            unique_together={('career', 'skill')},
        ),
    ]
